M48
; DRILL file {KiCad 9.0.6} date 2026-06-20T20:19:59+0200
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-06-20T20:19:59+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.6
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.800
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C2.000
%
G90
G05
T1
X137.2Y-101.3
X137.2Y-106.0
T2
X86.9Y-157.75
X94.5Y-95.95
X140.1Y-95.95
X164.2Y-157.65
M30
